-- travis-player: runtime controls
-- rewrites shader defines and reloads shader for live parameter adjustment

local opts = {
    shader_path        = "",   -- set via --script-opts=travis-shader_path=...
    alpha_floor        = 0.05,
    activity_threshold = 0.08,
    blur_radius        = 2.0,
    debug_mode         = 1,   -- start in heatmap so you can see it working
    enabled            = true,
}

require("mp.options").read_options(opts, "travis")

local shader_path = nil

local SHADER_TEMPLATE = [[
// travis-player motion mask shader
// generated by travis_controls.lua

#define ALPHA_FLOOR {{ALPHA_FLOOR}}
#define ACTIVITY_THRESHOLD {{ACTIVITY_THRESHOLD}}
#define BLUR_R {{BLUR_R}}
#define DEBUG_MODE {{DEBUG_MODE}}

//!HOOK OUTPUT
//!BIND HOOKED
//!BIND TRAVIS_PREV
//!DESC travis-player: motion compare

float luma(vec3 c) {
    return dot(c, vec3(0.2126, 0.7152, 0.0722));
}

float pixel_activity(vec2 pos) {
    float curr = luma(HOOKED_tex(pos).rgb);
    float prev = luma(TRAVIS_PREV_tex(pos).rgb);
    return smoothstep(ACTIVITY_THRESHOLD * 0.5, ACTIVITY_THRESHOLD * 1.5, abs(curr - prev));
}

float activity_blurred(vec2 pos) {
    vec2 step = HOOKED_pt * BLUR_R;
    float acc = 0.0, weight = 0.0;
    for (int dy = -1; dy <= 1; dy++) {
        for (int dx = -1; dx <= 1; dx++) {
            float w = 1.0 / (1.0 + float(abs(dx) + abs(dy)));
            acc    += pixel_activity(pos + vec2(float(dx), float(dy)) * step) * w;
            weight += w;
        }
    }
    return acc / weight;
}

vec4 hook() {
    vec4  color = HOOKED_tex(HOOKED_pos);
    float act   = activity_blurred(HOOKED_pos);
    float alpha = mix(ALPHA_FLOOR, 1.0, act);

#if DEBUG_MODE == 1
    vec3 heat = mix(vec3(0.0, 0.2, 1.0), vec3(1.0, 0.1, 0.0), act);
    return vec4(mix(color.rgb, heat, 0.7), 1.0);
#elif DEBUG_MODE == 2
    return vec4(vec3(step(0.5, act)), 1.0);
#else
    return vec4(color.rgb, alpha);
#endif
}

//!HOOK OUTPUT
//!BIND HOOKED
//!SAVE TRAVIS_PREV
//!DESC travis-player: save frame

vec4 hook() {
    return HOOKED_tex(HOOKED_pos);
}
]]

local function resolve_shader_path()
    if opts.shader_path ~= "" then
        return opts.shader_path:gsub("\\", "/")
    end
    -- fallback: try working directory
    local cwd = mp.get_property("working-directory") or ""
    cwd = cwd:gsub("\\", "/"):gsub("/$", "")
    return cwd .. "/shaders/motion_mask.glsl"
end

local function write_shader()
    if not shader_path then return false end
    local content = SHADER_TEMPLATE
        :gsub("{{ALPHA_FLOOR}}",        string.format("%.4f", opts.alpha_floor))
        :gsub("{{ACTIVITY_THRESHOLD}}", string.format("%.4f", opts.activity_threshold))
        :gsub("{{BLUR_R}}",             string.format("%.2f", opts.blur_radius))
        :gsub("{{DEBUG_MODE}}",         tostring(opts.debug_mode))

    local f = io.open(shader_path, "w")
    if not f then
        mp.msg.warn("could not write shader to " .. shader_path)
        return false
    end
    f:write(content)
    f:close()
    return true
end

local function reload_shader()
    if not shader_path or not opts.enabled then return end
    if not write_shader() then return end

    -- remove first (ignore error if not loaded yet), then re-add
    local ok, err = pcall(function()
        mp.commandv("change-list", "glsl-shaders", "remove", shader_path)
    end)

    -- try both property names (mpv version compat)
    local added = false
    ok, err = pcall(function()
        mp.commandv("change-list", "glsl-shaders", "append", shader_path)
        added = true
    end)
    if not ok then
        mp.msg.warn("change-list append failed: " .. tostring(err))
        -- fallback: set directly
        ok, err = pcall(function()
            mp.set_property("glsl-shaders", shader_path)
            added = true
        end)
        if not ok then
            mp.msg.warn("set_property fallback failed: " .. tostring(err))
        end
    end

    if added then
        mp.msg.info("shader (re)loaded")
    end
end

local function clamp(v, lo, hi)
    return math.max(lo, math.min(hi, v))
end

local function osd(msg, duration)
    mp.osd_message("[travis] " .. msg, duration or 2)
end

local function toggle()
    opts.enabled = not opts.enabled
    if opts.enabled then
        reload_shader()
        osd("ON")
    else
        if shader_path then
            mp.commandv("change-list", "glsl-shaders", "remove", shader_path)
        end
        osd("OFF")
    end
end

local function adjust(param, delta, label, lo, hi, fmt)
    opts[param] = clamp(opts[param] + delta, lo, hi)
    reload_shader()
    osd(string.format("%s → " .. (fmt or "%.3f"), label, opts[param]))
end

local function cycle_debug()
    opts.debug_mode = (opts.debug_mode + 1) % 3
    local names = {"normal", "heatmap", "binary"}
    reload_shader()
    osd("debug: " .. names[opts.debug_mode + 1])
end

local function show_status()
    osd(string.format(
        "alpha=%.2f  thresh=%.2f  blur=%.1f  debug=%s  [%s]",
        opts.alpha_floor, opts.activity_threshold, opts.blur_radius,
        ({"normal","heatmap","binary"})[opts.debug_mode + 1],
        opts.enabled and "ON" or "OFF"
    ), 4)
end

mp.add_key_binding("shift+m",    "travis-toggle",      toggle)  -- T conflicts with mpv on-top
mp.add_key_binding("F9",         "travis-status",      show_status)
mp.add_key_binding("F10",        "travis-debug-cycle", cycle_debug)
mp.add_key_binding("ctrl+UP",    "travis-alpha-up",    function() adjust("alpha_floor",        0.05, "alpha",  0.0, 1.0) end)
mp.add_key_binding("ctrl+DOWN",  "travis-alpha-down",  function() adjust("alpha_floor",       -0.05, "alpha",  0.0, 1.0) end)
mp.add_key_binding("ctrl+RIGHT", "travis-thresh-up",   function() adjust("activity_threshold", 0.01, "thresh", 0.01, 0.5) end)
mp.add_key_binding("ctrl+LEFT",  "travis-thresh-down", function() adjust("activity_threshold",-0.01, "thresh", 0.01, 0.5) end)
mp.add_key_binding("alt+RIGHT",  "travis-blur-up",     function() adjust("blur_radius",        0.5,  "blur",   0.0, 8.0, "%.1f") end)
mp.add_key_binding("alt+LEFT",   "travis-blur-down",   function() adjust("blur_radius",       -0.5,  "blur",   0.0, 8.0, "%.1f") end)

mp.register_event("file-loaded", function()
    shader_path = resolve_shader_path()
    if not shader_path then
        mp.msg.warn("could not resolve shader path")
        return
    end
    mp.msg.info("shader path: " .. shader_path)
    -- shader is already loaded via --glsl-shaders on command line
    -- write current params to file so next explicit reload picks them up
    write_shader()
    osd("ready  M=toggle  F9=status  F10=debug", 3)
end)
